INSERT INTO categories (name, group_name, entry_type, display_order) VALUES
-- Renda Passiva
('CDI-Liquidez',               'RENDA_PASSIVA',            'RECEITA', 10),
('Rendimentos de FIIs',        'RENDA_PASSIVA',            'RECEITA', 20),
('JCP',                        'RENDA_PASSIVA',            'RECEITA', 30),
('Dividendos-Ações BR',        'RENDA_PASSIVA',            'RECEITA', 40),
('Exterior-Dividendos',        'RENDA_PASSIVA',            'RECEITA', 50),
('Juros-CRI/CRA/DEB',          'RENDA_PASSIVA',            'RECEITA', 60),
('Amortizações-R.Fixa',        'RENDA_PASSIVA',            'RECEITA', 70),
('ETFs-Renda Fixa',            'RENDA_PASSIVA',            'RECEITA', 80),
-- Renda Ativa PJ
('Honorários (PF)',             'RENDA_ATIVA_PJ',           'RECEITA', 10),
('Dividendos Empresa',         'RENDA_ATIVA_PJ',           'RECEITA', 20),
('Pró Labore',                 'RENDA_ATIVA_PJ',           'RECEITA', 30),
('Adriele',                    'RENDA_ATIVA_PJ',           'RECEITA', 40),
-- Renda Ativa Investimentos
('Venda Ações BR-Trib',        'RENDA_ATIVA_INV',          'RECEITA', 10),
('Venda Ações Isento',         'RENDA_ATIVA_INV',          'RECEITA', 20),
('Venda de FIIs',              'RENDA_ATIVA_INV',          'RECEITA', 30),
('Venda Criptos',              'RENDA_ATIVA_INV',          'RECEITA', 40),
('Venda Ativos EUA',           'RENDA_ATIVA_INV',          'RECEITA', 50),
('Alienação de Bens',          'RENDA_ATIVA_INV',          'RECEITA', 60),
-- Despesas Essenciais
('Aluguel',                    'DESPESAS_ESSENCIAIS',      'DESPESA', 10),
('Condomínio',                 'DESPESAS_ESSENCIAIS',      'DESPESA', 20),
('IPTU',                       'DESPESAS_ESSENCIAIS',      'DESPESA', 30),
('Ambiental/Água',             'DESPESAS_ESSENCIAIS',      'DESPESA', 40),
('Energia',                    'DESPESAS_ESSENCIAIS',      'DESPESA', 50),
('Gás',                        'DESPESAS_ESSENCIAIS',      'DESPESA', 60),
('Internet',                   'DESPESAS_ESSENCIAIS',      'DESPESA', 70),
('Faxineira',                  'DESPESAS_ESSENCIAIS',      'DESPESA', 80),
('Celular',                    'DESPESAS_ESSENCIAIS',      'DESPESA', 90),
('Supermercado',               'DESPESAS_ESSENCIAIS',      'DESPESA', 100),
('Ifood/Pedidos',              'DESPESAS_ESSENCIAIS',      'DESPESA', 110),
('Combustível',                'DESPESAS_ESSENCIAIS',      'DESPESA', 120),
('Seguro',                     'DESPESAS_ESSENCIAIS',      'DESPESA', 130),
('Lava-jato',                  'DESPESAS_ESSENCIAIS',      'DESPESA', 140),
('Manutenção',                 'DESPESAS_ESSENCIAIS',      'DESPESA', 150),
('Estacionamento',             'DESPESAS_ESSENCIAIS',      'DESPESA', 160),
('Multas',                     'DESPESAS_ESSENCIAIS',      'DESPESA', 170),
('IPVA',                       'DESPESAS_ESSENCIAIS',      'DESPESA', 180),
('Academia/Natação',           'DESPESAS_ESSENCIAIS',      'DESPESA', 190),
('Salão',                      'DESPESAS_ESSENCIAIS',      'DESPESA', 200),
('Banho e Tosa',               'DESPESAS_ESSENCIAIS',      'DESPESA', 210),
('Ração/Biscoitos',            'DESPESAS_ESSENCIAIS',      'DESPESA', 220),
('Streamings',                 'DESPESAS_ESSENCIAIS',      'DESPESA', 230),
('Aplicativos (APPs)',         'DESPESAS_ESSENCIAIS',      'DESPESA', 240),
('Farmácia',                   'DESPESAS_ESSENCIAIS',      'DESPESA', 250),
('Seguro de Vida',             'DESPESAS_ESSENCIAIS',      'DESPESA', 260),
('Impostos (MEI, IRPF, OAB, CRP)', 'DESPESAS_ESSENCIAIS', 'DESPESA', 270),
-- Despesas Discricionárias
('Cartão de Crédito (Compras)',       'DESPESAS_DISCRICIONARIAS', 'DESPESA', 10),
('Bares/Cafés e Restaurantes',        'DESPESAS_DISCRICIONARIAS', 'DESPESA', 20),
('Estética',                          'DESPESAS_DISCRICIONARIAS', 'DESPESA', 30),
('Creche/Brinquedos/Veterinário',     'DESPESAS_DISCRICIONARIAS', 'DESPESA', 40),
('Viagens',                           'DESPESAS_DISCRICIONARIAS', 'DESPESA', 50),
('Presentes/Doações',                 'DESPESAS_DISCRICIONARIAS', 'DESPESA', 60),
('Roupas/Calçados',                   'DESPESAS_DISCRICIONARIAS', 'DESPESA', 70),
('Saúde - Médico/Dentista',           'DESPESAS_DISCRICIONARIAS', 'DESPESA', 80),
('Educação - Cursos/Livros',          'DESPESAS_DISCRICIONARIAS', 'DESPESA', 90),
('Outros',                            'DESPESAS_DISCRICIONARIAS', 'DESPESA', 100);
